# 4. Visualizing the most relevant MSc degrees

In [2]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [3]:
df = pd.read_csv("masters_dataset.csv")
df

,url,courseName,universityName,facultyName,fullTime,description,startDate,fees,modality,duration,city,country,administator
0,https://www.findamasters.com/masters-degrees/c...,3D Design for Virtual Environments - MSc,Glasgow Caledonian University,School of Engineering and Built Environment,True,3D visualisation and animation play a role in ...,September,FeesPlease see the university website for furt...,MSc,1 year full-time,Glasgow,United Kingdom,On Campus
1,https://www.findamasters.com/masters-degrees/c...,Accounting and Finance - MSc,University of Leeds,Leeds University Business School,True,Businesses and governments rely on sound finan...,September,"FeesUK: £18,000 (Total)International: £34,750 ...",MSc,1 year full time,Leeds,United Kingdom,On Campus
2,https://www.findamasters.com/masters-degrees/c...,"Accounting, Accountability & Financial Managem...",King’s College London,King’s Business School,True,"Our Accounting, Accountability & Financial Man...",September,FeesPlease see the university website for furt...,MSc,1 year FT,London,United Kingdom,On Campus
3,https://www.findamasters.com/masters-degrees/c...,"Accounting, Financial Management and Digital B...",University of Reading,Henley Business School,True,Embark on a professional accounting career wit...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Reading,United Kingdom,On Campus
4,https://www.findamasters.com/masters-degrees/c...,Addictions MSc,King’s College London,"Institute of Psychiatry, Psychology and Neuros...",True,Join us for an online session for prospective ...,September,FeesPlease see the university website for furt...,MSc,One year FT,London,United Kingdom,On Campus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5300,https://www.findamasters.com/masters-degrees/c...,Materials and Manufacturing,Jonkoping University,Masters Programmes,True,Numerical methods and knowledge about the rela...,See Course,FeesPlease see the university website for furt...,MSc,2 Years Full Time,Jonkoping,Sweden,On Campus
5301,https://www.findamasters.com/masters-degrees/c...,Materials and Molecular Modelling MSc,University College London,Department of Chemistry,True,Register your interest in graduate study at UC...,September,"FeesFull time - £14,100",MSc,1 year full time,London,United Kingdom,On Campus
5302,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry - MSc,University of Bradford,Faculty of Life Sciences,True,We provide a unique Master’s education in Mate...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Bradford,United Kingdom,On Campus
5303,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry MSc,University of Edinburgh,School of Chemistry,True,Programme descriptionMaterials Chemistry has e...,September,FeesTuition fees vary between degree programme...,MSc,1 year full-time,Edinburgh,United Kingdom,On Campus
5304,https://www.findamasters.com/masters-degrees/c...,Materials Engineering,University of Padua,School of Engineering,True,TheMaster's degree Materials Engineeringis an ...,October,FeesOur tuition fees will not exceed 2700 euro...,MSc,2 years,Padua,Italy,On Campus

In [4]:
interesting_cols = ["universityName","city","country"]
interesting_cols = ["city","country"]
# df[interesting_cols].drop_duplicates().to_csv("city_country.csv")

##### alternative approach

In [5]:
from geopy.geocoders import Nominatim

# geolocator = Nominatim(user_agent="geoapiExercises")
geolocator = Nominatim(user_agent="gettingCityCoords")
# from geopy.geocoders import Photon
# geolocator = Photon(user_agent="my-application")


def get_lat_lng(city, country):
   location = geolocator.geocode(f"{city}, {country}")
   if location:
       return location.latitude, location.longitude
   else:
       return None, None

cities = {
   1484: {"city": None, "country": None},
   1520: {"city": "Malmo", "country": "Sweden"},
   2067: {"city": "Egham", "country": "United Kingdom"},
   2325: {"city": "Cluj Napoca", "country": "Romania"},
   2742: {"city": "L Aquila", "country": "Italy"},
   3286: {"city": "Thessaloniki", "country": "Greece"},
   3289: {"city": "Naestved", "country": "Denmark"},
   3290: {"city": "Solna", "country": "Sweden"},
   3291: {"city": "Zurich", "country": "Switzerland"},
   3295: {"city": "Saarbrucken", "country": "Germany"},
   4515: {"city": "Luneburg", "country": "Germany"},
   4803: {"city": "Gottingen", "country": "Germany"},
   5130: {"city": "Besancon", "country": "France"},
   5131: {"city": "Frankfurt am Main", "country": "Germany"},
   5227: {"city": "Velp", "country": "Netherlands"},
   5375: {"city": "Blackburg", "country": "USA"},
   5395: {"city": "Astana", "country": "Kazakstan"},
   5428: {"city": "Freiburg", "country": "Germany"},
   5477: {"city": "St Catherines", "country": "Canada"},
}

for city_id, city_info in cities.items():
   lat, lng = get_lat_lng(city_info["city"], city_info["country"])
   city_info["lat"] = lat
   city_info["lng"] = lng

In [6]:
cities_df = pd.DataFrame(cities).T.reset_index()
cities_df.columns = ["city_id", "city", "country", "lat", "lng"]

cities_df = cities_df[["city", "country", "lat", "lng"]]
cities_df

                 city         country        lat        lng
0                 NaN             NaN  44.937967    7.54004
1               Malmo          Sweden  55.605293  13.000157
2               Egham  United Kingdom  51.431258  -0.547308
3         Cluj Napoca         Romania  46.769379  23.589954
4            L Aquila           Italy  42.136885  13.610341
5        Thessaloniki          Greece  40.640317  22.935272
6            Naestved         Denmark  55.232825   11.76741
7               Solna          Sweden  59.361367  18.001369
8              Zurich     Switzerland  47.374449   8.541042
9         Saarbrucken         Germany  49.234362   6.996379
10           Luneburg         Germany  53.248706  10.407855
11          Gottingen         Germany  51.532833   9.935181
12           Besancon          France  47.238022   6.024362
13  Frankfurt am Main         Germany  50.110644   8.682092
14               Velp     Netherlands  51.995867   5.975125
15          Blackburg             USA  35.226493 -89.875684
16             Astana       Kazakstan   51.12822  71.430668
17           Freiburg         Germany   47.99609     7.8494
18      St Catherines          Canada  46.192008 -63.297381

In [7]:
# read world cities, thanks to https://simplemaps.com/data/world-cities (we used this source :) )
worldcities = pd.read_csv("worldcities.csv", usecols=["city", "country", "lat","lng"])
worldcities

              city      lat       lng    country
0            Tokyo  35.6897  139.6922      Japan
1          Jakarta  -6.1750  106.8275  Indonesia
2            Delhi  28.6100   77.2300      India
3        Guangzhou  23.1300  113.2600      China
4           Mumbai  19.0761   72.8775      India
...            ...      ...       ...        ...
44686        Numto  63.6667   71.3333     Russia
44687         Nord  81.7166  -17.8000  Greenland
44688  Timmiarmiut  62.5333  -42.2167  Greenland
44689   San Rafael -16.7795  -60.6799    Bolivia
44690      Nordvik  74.0165  111.5100     Russia

[44691 rows x 4 columns]

In [8]:
city_mapping = {
    "United States" : "USA"
}

# def map_cities():
#     if

In [9]:
worldcities["country"] = worldcities["country"].apply(lambda row: "USA" if row == "United States" else row)
worldcities[worldcities["city"]=="New York"]

        city      lat      lng country
11  New York  40.6943 -73.9249     USA

In [10]:
additional_coordinates1_data = {
 ('Isafjorour', 'Iceland'): (-19.020835, 64.963051),
 ('Coleraine', 'United Kingdom'): (-6.750000, 54.733333),
 ('Clear Water Bay', 'Hong Kong'): (114.1095, 22.3964),
 ('Boras', 'Sweden'): (13.2764, 58.1102),
 ('Hull', 'United Kingdom'): (-0.3111, 53.7498),
 ('Cardiff', 'United Kingdom'): (-3.1791, 51.4816),
 ('St Andrews', 'United Kingdom'): (-2.4208, 56.3391),
 ('Stoke on Trent', 'United Kingdom'): (-1.8024, 52.9439),
 ('Swansea', 'United Kingdom'): (-3.9433, 51.6275),
 ('Linkoping', 'Sweden'): (15.6027, 58.4128),
 ('Jonkoping', 'Sweden'): (14.1420, 57.7951),
 ('St Cloud', 'USA'): (-94.2000, 45.5261),
 ('Washington DC', 'USA'): (-77.0369, 38.9072),
 ('Thuwal', 'Saudi Arabia'): (46.6370, 24.7114),
 ('Padua', 'Italy'): (11.8796, 45.4064)
}

In [11]:
additional_coordinates1 = pd.DataFrame(list(additional_coordinates1_data.items()), columns=['City-Country', 'Coordinates'])
additional_coordinates1[['city', 'country']] = pd.DataFrame(additional_coordinates1['City-Country'].tolist(), index=additional_coordinates1.index)
additional_coordinates1[['lng', 'lat']] = pd.DataFrame(additional_coordinates1['Coordinates'].tolist(), index=additional_coordinates1.index)
additional_coordinates1 = additional_coordinates1[["city","country","lng","lat"]]
additional_coordinates1

               city         country         lng        lat
0        Isafjorour         Iceland  -19.020835  64.963051
1         Coleraine  United Kingdom   -6.750000  54.733333
2   Clear Water Bay       Hong Kong  114.109500  22.396400
3             Boras          Sweden   13.276400  58.110200
4              Hull  United Kingdom   -0.311100  53.749800
5           Cardiff  United Kingdom   -3.179100  51.481600
6        St Andrews  United Kingdom   -2.420800  56.339100
7    Stoke on Trent  United Kingdom   -1.802400  52.943900
8           Swansea  United Kingdom   -3.943300  51.627500
9         Linkoping          Sweden   15.602700  58.412800
10        Jonkoping          Sweden   14.142000  57.795100
11         St Cloud             USA  -94.200000  45.526100
12    Washington DC             USA  -77.036900  38.907200
13           Thuwal    Saudi Arabia   46.637000  24.711400
14            Padua           Italy   11.879600  45.406400

In [12]:
worldcities = pd.concat([worldcities, additional_coordinates1, cities_df])
worldcities

             city        lat        lng      country
0           Tokyo    35.6897   139.6922        Japan
1         Jakarta     -6.175   106.8275    Indonesia
2           Delhi      28.61      77.23        India
3       Guangzhou      23.13     113.26        China
4          Mumbai    19.0761    72.8775        India
..            ...        ...        ...          ...
14           Velp  51.995867   5.975125  Netherlands
15      Blackburg  35.226493 -89.875684          USA
16         Astana   51.12822  71.430668    Kazakstan
17       Freiburg   47.99609     7.8494      Germany
18  St Catherines  46.192008 -63.297381       Canada

[44725 rows x 4 columns]

In [13]:
merged_df = pd.merge(left = df, right = worldcities, left_on=["city","country"], right_on=["city","country"], how="left")
merged_df

,url,courseName,universityName,facultyName,fullTime,description,startDate,fees,modality,duration,city,country,administator,lat,lng
0,https://www.findamasters.com/masters-degrees/c...,3D Design for Virtual Environments - MSc,Glasgow Caledonian University,School of Engineering and Built Environment,True,3D visualisation and animation play a role in ...,September,FeesPlease see the university website for furt...,MSc,1 year full-time,Glasgow,United Kingdom,On Campus,55.8611,-4.25
1,https://www.findamasters.com/masters-degrees/c...,Accounting and Finance - MSc,University of Leeds,Leeds University Business School,True,Businesses and governments rely on sound finan...,September,"FeesUK: £18,000 (Total)International: £34,750 ...",MSc,1 year full time,Leeds,United Kingdom,On Campus,53.8003,-1.5497
2,https://www.findamasters.com/masters-degrees/c...,"Accounting, Accountability & Financial Managem...",King’s College London,King’s Business School,True,"Our Accounting, Accountability & Financial Man...",September,FeesPlease see the university website for furt...,MSc,1 year FT,London,United Kingdom,On Campus,51.5072,-0.1275
3,https://www.findamasters.com/masters-degrees/c...,"Accounting, Financial Management and Digital B...",University of Reading,Henley Business School,True,Embark on a professional accounting career wit...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Reading,United Kingdom,On Campus,51.4542,-0.9731
4,https://www.findamasters.com/masters-degrees/c...,Addictions MSc,King’s College London,"Institute of Psychiatry, Psychology and Neuros...",True,Join us for an online session for prospective ...,September,FeesPlease see the university website for furt...,MSc,One year FT,London,United Kingdom,On Campus,51.5072,-0.1275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5620,https://www.findamasters.com/masters-degrees/c...,Materials and Manufacturing,Jonkoping University,Masters Programmes,True,Numerical methods and knowledge about the rela...,See Course,FeesPlease see the university website for furt...,MSc,2 Years Full Time,Jonkoping,Sweden,On Campus,57.7951,14.142
5621,https://www.findamasters.com/masters-degrees/c...,Materials and Molecular Modelling MSc,University College London,Department of Chemistry,True,Register your interest in graduate study at UC...,September,"FeesFull time - £14,100",MSc,1 year full time,London,United Kingdom,On Campus,51.5072,-0.1275
5622,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry - MSc,University of Bradford,Faculty of Life Sciences,True,We provide a unique Master’s education in Mate...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Bradford,United Kingdom,On Campus,53.8,-1.75
5623,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry MSc,University of Edinburgh,School of Chemistry,True,Programme descriptionMaterials Chemistry has e...,September,FeesTuition fees vary between degree programme...,MSc,1 year full-time,Edinburgh,United Kingdom,On Campus,55.9533,-3.1892
5624,https://www.findamasters.com/masters-degrees/c...,Materials Engineering,University of Padua,School of Engineering,True,TheMaster's degree Materials Engineeringis an ...,October,FeesOur tuition fees will not exceed 2700 euro...,MSc,2 years,Padua,Italy,On Campus,45.4064,11.8796

In [14]:
nans = merged_df[merged_df["lat"].isnull() | merged_df["lng"].isnull()][["city","country","lat","lng"]].drop_duplicates()
print(len(nans[['city','country']]))
nans[['city','country']]

0

Empty DataFrame
Columns: [city, country]
Index: []

In [15]:
worldcities[worldcities["city"]=="New York"]
worldcities[worldcities["country"]=="Iceland"]
worldcities[worldcities["country"]=="Hong Kong"]
worldcities[worldcities["city"]=="Coleraine"]

worldcities[ worldcities['city'].isin(nans["city"])]['city']

Series([], Name: city, dtype: object)

In [18]:
# merged_df.to_csv("masters_courses_with_coords123123", index=False)
merged_df

,url,courseName,universityName,facultyName,fullTime,description,startDate,fees,modality,duration,city,country,administator,lat,lng
0,https://www.findamasters.com/masters-degrees/c...,3D Design for Virtual Environments - MSc,Glasgow Caledonian University,School of Engineering and Built Environment,True,3D visualisation and animation play a role in ...,September,FeesPlease see the university website for furt...,MSc,1 year full-time,Glasgow,United Kingdom,On Campus,55.8611,-4.25
1,https://www.findamasters.com/masters-degrees/c...,Accounting and Finance - MSc,University of Leeds,Leeds University Business School,True,Businesses and governments rely on sound finan...,September,"FeesUK: £18,000 (Total)International: £34,750 ...",MSc,1 year full time,Leeds,United Kingdom,On Campus,53.8003,-1.5497
2,https://www.findamasters.com/masters-degrees/c...,"Accounting, Accountability & Financial Managem...",King’s College London,King’s Business School,True,"Our Accounting, Accountability & Financial Man...",September,FeesPlease see the university website for furt...,MSc,1 year FT,London,United Kingdom,On Campus,51.5072,-0.1275
3,https://www.findamasters.com/masters-degrees/c...,"Accounting, Financial Management and Digital B...",University of Reading,Henley Business School,True,Embark on a professional accounting career wit...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Reading,United Kingdom,On Campus,51.4542,-0.9731
4,https://www.findamasters.com/masters-degrees/c...,Addictions MSc,King’s College London,"Institute of Psychiatry, Psychology and Neuros...",True,Join us for an online session for prospective ...,September,FeesPlease see the university website for furt...,MSc,One year FT,London,United Kingdom,On Campus,51.5072,-0.1275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5620,https://www.findamasters.com/masters-degrees/c...,Materials and Manufacturing,Jonkoping University,Masters Programmes,True,Numerical methods and knowledge about the rela...,See Course,FeesPlease see the university website for furt...,MSc,2 Years Full Time,Jonkoping,Sweden,On Campus,57.7951,14.142
5621,https://www.findamasters.com/masters-degrees/c...,Materials and Molecular Modelling MSc,University College London,Department of Chemistry,True,Register your interest in graduate study at UC...,September,"FeesFull time - £14,100",MSc,1 year full time,London,United Kingdom,On Campus,51.5072,-0.1275
5622,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry - MSc,University of Bradford,Faculty of Life Sciences,True,We provide a unique Master’s education in Mate...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Bradford,United Kingdom,On Campus,53.8,-1.75
5623,https://www.findamasters.com/masters-degrees/c...,Materials Chemistry MSc,University of Edinburgh,School of Chemistry,True,Programme descriptionMaterials Chemistry has e...,September,FeesTuition fees vary between degree programme...,MSc,1 year full-time,Edinburgh,United Kingdom,On Campus,55.9533,-3.1892
5624,https://www.findamasters.com/masters-degrees/c...,Materials Engineering,University of Padua,School of Engineering,True,TheMaster's degree Materials Engineeringis an ...,October,FeesOur tuition fees will not exceed 2700 euro...,MSc,2 years,Padua,Italy,On Campus,45.4064,11.8796

In [29]:
merged_df_head = merged_df.loc[:10,:]
merged_df_head

,url,courseName,universityName,facultyName,fullTime,description,startDate,fees,modality,duration,city,country,administator,lat,lng
0,https://www.findamasters.com/masters-degrees/c...,3D Design for Virtual Environments - MSc,Glasgow Caledonian University,School of Engineering and Built Environment,True,3D visualisation and animation play a role in ...,September,FeesPlease see the university website for furt...,MSc,1 year full-time,Glasgow,United Kingdom,On Campus,55.8611,-4.25
1,https://www.findamasters.com/masters-degrees/c...,Accounting and Finance - MSc,University of Leeds,Leeds University Business School,True,Businesses and governments rely on sound finan...,September,"FeesUK: £18,000 (Total)International: £34,750 ...",MSc,1 year full time,Leeds,United Kingdom,On Campus,53.8003,-1.5497
2,https://www.findamasters.com/masters-degrees/c...,"Accounting, Accountability & Financial Managem...",King’s College London,King’s Business School,True,"Our Accounting, Accountability & Financial Man...",September,FeesPlease see the university website for furt...,MSc,1 year FT,London,United Kingdom,On Campus,51.5072,-0.1275
3,https://www.findamasters.com/masters-degrees/c...,"Accounting, Financial Management and Digital B...",University of Reading,Henley Business School,True,Embark on a professional accounting career wit...,September,FeesPlease see the university website for furt...,MSc,1 year full time,Reading,United Kingdom,On Campus,51.4542,-0.9731
4,https://www.findamasters.com/masters-degrees/c...,Addictions MSc,King’s College London,"Institute of Psychiatry, Psychology and Neuros...",True,Join us for an online session for prospective ...,September,FeesPlease see the university website for furt...,MSc,One year FT,London,United Kingdom,On Campus,51.5072,-0.1275
5,https://www.findamasters.com/masters-degrees/c...,Advanced Chemical Engineering - MSc,University of Leeds,School of Chemical and Process Engineering,True,The Advanced Chemical Engineering MSc at Leeds...,September,"FeesUK: £13,750 (Total)International: £31,000 ...",MSc,1 year full time,Leeds,United Kingdom,On Campus,53.8003,-1.5497
6,https://www.findamasters.com/masters-degrees/c...,Advanced Master in Financial Markets,Solvay Brussels School,Economics and Management,True,Programme overviewThe Advanced Master in Finan...,September,Fees18.000 €,"MA,MSc,Other,Pre-Masters,Masters Module",1 year,Brussels,Belgium,On Campus,50.8467,4.3525
7,https://www.findamasters.com/masters-degrees/c...,Advanced Master in Innovation & Strategic Mana...,Solvay Brussels School,Economics and Management,True,Programme overviewThe Advanced Master in Innov...,September,Fees18.000 €,"MA,MSc,Other,Masters Module,Pre-Masters",10 months,Brussels,Belgium,On Campus,50.8467,4.3525
8,https://www.findamasters.com/masters-degrees/c...,Advanced Physiotherapy Practice - MSc,Glasgow Caledonian University,School of Health and Life Sciences,True,Progress your career as a physiotherapist with...,"January, September",FeesPlease see the university website for furt...,MSc,1 Year Full Time / 2-3 Years Part Time,Glasgow,United Kingdom,On Campus,55.8611,-4.25
9,https://www.findamasters.com/masters-degrees/c...,Agricultural Sciences - MSc (Agriculture and F...,University of Helsinki,International Masters Degree Programmes,True,Goal of the pro­grammeWould you like to be inv...,September,FeesTuition fee per year (non-EU/EEA students)...,MSc,2 years,Helsinki,Finland,On Campus,60.1708,24.9375
10,https://www.findamasters.com/masters-degrees/c...,"Agricultural, Environmental and Resource Econo...",University of Helsinki,International Masters Degree Programmes,True,Goal of the pro­grammeAre you looking forward ...,September,FeesTuition fee per year (non-EU/EEA students)...,MSc,2 years,Helsinki,Finland,On Campus,60.1708,24.9375

In [31]:
import geopandas as gpd
from shapely.geometry import Point
import folium

# Create a GeoDataFrame
gdf = gpd.GeoDataFrame(merged_df_head, geometry=gpd.points_from_xy(merged_df_head.lng, merged_df_head.lat))

# Create a Folium map centered at the mean location of the universities
m = folium.Map(location=[merged_df_head['lat'].mean(), merged_df_head['lng'].mean()], zoom_start=13)

# Add a marker for each university
for index, row in gdf.iterrows():
   # print(index)
   # print(row)
   folium.Marker([row['lat'], row['lng']], popup=row['universityName']).add_to(m)

# Show the map

In [32]:
# show map
m

In [33]:
for index, row in gdf.iterrows():
   popup_text = f"University: {row['universityName']}<br>Course: {row['courseName']}<br>Fee: {row['fees']}"
   folium.Marker([row['lat'], row['lng']], popup=popup_text).add_to(m)
m